version: '3'

services:
  postgres_service:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_service:/docker-entrypoint-initdb.d
    restart: on-failure
    ports:
      - 5432:5432
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  redis_service:
    image: redis:6
    container_name: redis_service
    command: redis-server --appendonly yes
    volumes:
      - ./redis_service:/data
    restart: on-failure
    ports:
      - 6379:6379

  adminer:
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - 8080:8080

  django_service:
    build: ./django_service
    container_name: django_service
    working_dir: /app
    volumes:
      - ./django_service:/app
    command: bash -c "make"
    env_file:
      - ./django_service/.env
    environment:
      TZ: "Asia/Novosibirsk"
    restart: on-failure
    ports:
      - 8000:8000
      - 8001:8001
    # depends_on:
    #   postgres_service:
    #     condition: service_healthy
